import React, { useEffect, useState } from 'react';
import { X } from 'lucide-react';

interface AIExplanationPanelProps {
  isOpen: boolean;
  onClose: () => void;
  selectedText: string;
  explanation: string;
}

export const AIExplanationPanel: React.FC<AIExplanationPanelProps> = ({
  isOpen,
  onClose,
  selectedText,
  explanation
}) => {
  const [isLoading, setIsLoading] = useState(false);
  const [showContent, setShowContent] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsLoading(true);
      setShowContent(false);
      
      // Simulate AI processing time
      const timer = setTimeout(() => {
        setIsLoading(false);
        setShowContent(true);
      }, 2000);

      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div 
      className={`absolute bottom-0 left-0 right-0 bg-[#1a1a1a] border-t border-gray-700 transition-transform duration-300 ease-out ${
        isOpen ? 'transform translate-y-0' : 'transform translate-y-full'
      }`}
      style={{ height: '60%' }}
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-700">
        <div className="flex items-center space-x-2">
          <div className="w-6 h-6 bg-[#0075ff] rounded-full flex items-center justify-center">
            <span className="text-white text-xs font-bold">AI</span>
          </div>
          <span className="text-white font-medium">AI Explanation</span>
        </div>
        <button
          onClick={onClose}
          className="text-gray-400 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Content */}
      <div className="p-4 h-full overflow-y-auto">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center h-32">
            <div className="flex space-x-1 mb-4">
              <div className="w-2 h-2 bg-[#0075ff] rounded-full animate-bounce"></div>
              <div className="w-2 h-2 bg-[#0075ff] rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
              <div className="w-2 h-2 bg-[#0075ff] rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
            </div>
            <p className="text-gray-400 text-sm">AI is analyzing the text...</p>
          </div>
        ) : showContent ? (
          <div className="space-y-4 animate-fade-in">
            {/* Selected Text */}
            <div className="bg-gray-800 rounded-lg p-3">
              <p className="text-gray-400 text-xs uppercase tracking-wide mb-1">Selected Text</p>
              <p className="text-white text-sm font-medium">"{selectedText}"</p>
            </div>

            {/* AI Explanation */}
            <div>
              <p className="text-gray-400 text-xs uppercase tracking-wide mb-2">Simple Explanation</p>
              <div className="bg-[#0075ff]/10 border border-[#0075ff]/20 rounded-lg p-4">
                <p className="text-gray-200 leading-relaxed text-sm">
                  {explanation}
                </p>
              </div>
            </div>

            {/* Additional Context */}
            <div className="bg-gray-800 rounded-lg p-3">
              <p className="text-gray-400 text-xs uppercase tracking-wide mb-1">Context</p>
              <p className="text-gray-300 text-sm">
                This explanation is generated by AI to help make complex research concepts more accessible. 
                The original paper contains more technical details.
              </p>
            </div>

            {/* Action Buttons */}
            <div className="flex space-x-2 pt-2">
              <button className="flex-1 bg-[#0075ff] text-white py-2 px-4 rounded-lg text-sm font-medium hover:bg-blue-600 transition-colors">
                Learn More
              </button>
              <button 
                onClick={onClose}
                className="flex-1 bg-gray-700 text-white py-2 px-4 rounded-lg text-sm font-medium hover:bg-gray-600 transition-colors"
              >
                Got It
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
};